export interface SelectOption {
  label: string;
  value: string;
  dataType: 'text' | 'date' | 'number' | 'checkbox';
}

export interface Field {
  label: string;
  value: string;
  selectOptions?: SelectOption[];
  dataType?: 'text' | 'date' | 'number' | 'checkbox';
}

export const fields: Field[] = [
  {
    label: 'File System - Close File',
    value: 'filesystem_closefile',
    selectOptions: [
      { label: 'آدرس عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'number' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر فایل', value: 'file_path', dataType: 'text' },
      { label: 'شناسه فایل', value: 'file_volume_guid', dataType: 'text' },
      { label: 'نوع فایل', value: 'file_volume_type', dataType: 'text' },
      { label: 'دستگاه متصل', value: 'file_volume_device', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه فرایند والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'File System - Create File',
    value: 'filesystem_createfile',
    selectOptions: [
      { label: 'آدرس عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'number' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر فایل', value: 'file_path', dataType: 'text' },
      { label: 'شناسه فایل', value: 'file_volume_guid', dataType: 'text' },
      { label: 'نوع فایل', value: 'file_volume_type', dataType: 'text' },
      { label: 'دستگاه متصل', value: 'file_volume_device', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه فرایند والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'File System - Data Readfull',
    value: 'filesystem_datareadfull',
    selectOptions: [
      { label: 'آدرس عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر فایل', value: 'file_path', dataType: 'text' },
      { label: 'شناسه حجم فایل', value: 'file_volume_guid', dataType: 'text' },
      { label: 'نوع حجم فایل', value: 'file_volume_type', dataType: 'text' },
      { label: 'دستگاه حجم فایل', value: 'file_volume_device', dataType: 'text' },
      { label: 'هش خام فایل', value: 'file_raw_hash', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه فرایند والد', value: 'parent_pid', dataType: 'number' },
    ],
  },

  {
    label: 'File System - Data Writefull',
    value: 'filesystem_datawritefull',
    selectOptions: [
      { label: 'آدرس عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر فایل', value: 'file_path', dataType: 'text' },
      { label: 'شناسه حجم فایل', value: 'file_volume_guid', dataType: 'text' },
      { label: 'نوع حجم فایل', value: 'file_volume_type', dataType: 'text' },
      { label: 'دستگاه حجم فایل', value: 'file_volume_device', dataType: 'text' },
      { label: 'هش فایل', value: 'file_raw_hash', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه فرایند والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'File System - Deletefile',
    value: 'filesystem_deletefile',
    dataType: 'text',
  },
  {
    label: 'File System - File Data Change',
    value: 'filesystem_filedatachange',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر فایل', value: 'file_path', dataType: 'text' },
      { label: 'شناسه فایل', value: 'file_volume_guid', dataType: 'text' },
      { label: 'نوع فایل', value: 'file_volume_type', dataType: 'text' },
      { label: 'دستگاه متصل', value: 'file_volume_device', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه فرایند والد', value: 'parent_pid', dataType: 'number' },
    ],
  },

  {
    label: 'Process - Create Process',
    value: 'process_createprocess',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'شناسه فرایند والد', value: 'parent_process_id', dataType: 'number' },
      { label: 'فایل فرایند', value: 'process_image_file', dataType: 'text' },
      { label: 'شناسه فرایند کاربر', value: 'process_user_sid', dataType: 'number' },
      { label: 'زمان ایجاد فرایند', value: 'process_creation_time', dataType: 'date' },
      { label: ' شناسه ایجاد کننده فرایند', value: 'process_creator_pid', dataType: 'number' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'خط فرمان فرایند', value: 'process_cmd_line', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'Process - Delete Process',
    value: 'process_deleteprocess',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'زمان پاک شدن فرایند', value: 'process_deletion_time', dataType: 'date' },
      { label: 'کد خروج فرایند', value: 'process_exit_code', dataType: 'number' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'Process - Open Process',
    value: 'process_openprocess',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'شناسه فرایند هدف', value: 'target_process_pid', dataType: 'number' },
      { label: 'آدرس پوشش شبکه', value: 'access_mask', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },

  {
    label: 'Registry - Create Key',
    value: 'registry_createkey',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر رجیستری', value: 'registry_path', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'Registry - Delete Key',
    value: 'registry_deletekey',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر رجیستری', value: 'registry_path', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'Registry - Delete Value',
    value: 'registry_deletevalue',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر رجیستری', value: 'registry_path', dataType: 'text' },
      { label: 'نام رجیستری', value: 'registry_name', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'Registry - Key NameChange',
    value: 'registry_keynamechanged',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر رجیستری', value: 'registry_path', dataType: 'text' },
      { label: 'نام کلید جدید', value: 'new_key_name', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },
  {
    label: 'Registry - Key ValueSet',
    value: 'registry_keyvalueset',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'زمان پردازنده', value: 'tick_time', dataType: 'date' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: ' وضعیت ارزیابی فرایند', value: 'process_is_evaluated', dataType: 'checkbox' },
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'نوع درایور', value: 'driver_type', dataType: 'text' },
      { label: 'مسیر رجیستری', value: 'registry_path', dataType: 'text' },
      { label: 'نام رجیستری', value: 'registry_name', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },

  {
    label: 'ETW - Network Connection Attempted Info',
    value: 'etw_network_connectionattemptedinfo',
    selectOptions: [
      { label: 'آدرس عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'نوع رویداد رادار', value: 'radar_event_entry_type', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'text' },
      { label: 'شناسه فرایند', value: 'process_id', dataType: 'text' },
      { label: 'نوع', value: 'etw_type', dataType: 'text' },
      { label: 'آدرس مبدا', value: 'src_ip', dataType: 'text' },
      { label: 'آدرس مقصد', value: 'dest_ip', dataType: 'text' },
      { label: 'پورت مبدا', value: 'src_port', dataType: 'text' },
      { label: 'پورت مقصد', value: 'dest_port', dataType: 'text' },
      { label: 'اندازه', value: 'size', dataType: 'text' },
      { label: 'شناسه اتصال', value: 'connection_id', dataType: 'text' },
      { label: 'رویداد', value: 'event', dataType: 'text' },
      { label: 'شناسه والد', value: 'parent_pid', dataType: 'number' },
    ],
  },

  {
    label: 'Quarantined Files',
    value: 'quarantined_files',
    selectOptions: [
      { label: 'شناسه عامل', value: 'agent_id', dataType: 'text' },
      { label: 'آدرس عامل', value: 'agent_ip', dataType: 'text' },
      { label: 'مسیر فایل فرایند والد', value: 'parent_process_file_path', dataType: 'text' },
      { label: 'مسیر فایل', value: 'accessed_file_path', dataType: 'text' },
      { label: 'شناسه فرایند', value: 'pid', dataType: 'number' },
      { label: 'امتیاز', value: 'score', dataType: 'number' },
      { label: 'زمان قرنطینه', value: 'quarantine_time', dataType: 'text' },
      { label: 'دلیل قرنطینه', value: 'quarantine_reason', dataType: 'text' },
      { label: 'اندازه فایل', value: 'file_size', dataType: 'text' },
      { label: 'تاریخ', value: 'timestamp', dataType: 'date' },
      { label: 'نام فایل', value: 'file_name', dataType: 'text' },
      { label: 'نشانه', value: 'tag', dataType: 'text' },
      { label: 'هش md5', value: 'hash_md5', dataType: 'text' },
      { label: 'هش sha256', value: 'hash_sha256', dataType: 'text' },
    ],
  },
];
