interface Field {
  field: string;
  headerName: string;
  dataType: 'number' | 'text' | 'date' | 'checkbox';
  isHeader: boolean;
}

interface Headers {
  [key: string]: Array<Field>;
}

const headers: Headers = {
  etw_sysmon_processcreate: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "CommandLine",
      headerName: "خط فرمان",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "Company",
      headerName: "سازمان",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "Description",
      headerName: "توضیحات",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "FileVersion",
      headerName: "نسخه فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "Hashes", headerName: "هش ها", dataType: "text", isHeader: true },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "IntegrityLevel",
      headerName: "سطح یکپارچگی",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "LogonGuid",
      headerName: "شناسه یکتای ورود",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "LogonId",
      headerName: "شناسه ورود",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "OriginalFileName",
      headerName: "نام اصلی فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ParentCommandLine",
      headerName: "خط فرمان والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ParentImage",
      headerName: "فایل والد",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "ParentProcessGuid",
      headerName: "شناسه یکتای پردازه والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ParentProcessId",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "ParentUser",
      headerName: "کاربر والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "Product",
      headerName: "محصول",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "TerminalSessionId",
      headerName: "شناسه نشست ترمینال",
      dataType: "number",
      isHeader: false,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: false },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه فرآیند ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "CurrentDirectory",
      headerName: "مسیر پوشه فعلی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_driverload: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    { field: "Hashes", headerName: "هش ها", dataType: "text", isHeader: true },
    {
      field: "ImageLoaded",
      headerName: "فایل بازگذاری شده",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "Signature",
      headerName: "امضاء",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "SignatureStatus",
      headerName: "وضعیت امضاء",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "Signed",
      headerName: "امضاء شده",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_filecreate: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "CreationUtcTime",
      headerName: "تاریخ دقیق ایجاد",
      dataType: "text",
      isHeader: false,
    },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "TargetFilename",
      headerName: "نام فایل هدف",
      dataType: "text",
      isHeader: true,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: false },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_networkconnection: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "DestinationHostname",
      headerName: "نام میزبان مقصد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "DestinationIp",
      headerName: "آدرس مقصد",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "DestinationIsIpv6",
      headerName: "وضعیت آدرس نسخه ۶ مقصد",
      dataType: "checkbox",
      isHeader: false,
    },
    {
      field: "DestinationPort",
      headerName: "شماره پورت مقصد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "DestinationPortName",
      headerName: "نام پورت مقصد",
      dataType: "text",
      isHeader: false,
    },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "Initiated",
      headerName: "وضعیت اولیه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "Protocol",
      headerName: "پروتکل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SourceHostname",
      headerName: "نام میزبان مبداء",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SourceIp",
      headerName: "آدرس مبداء",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "SourceIsIpv6",
      headerName: "وضعیت آدرس نسخه ۶ مبداء",
      dataType: "checkbox",
      isHeader: false,
    },
    {
      field: "SourcePort",
      headerName: "شماره پورت مبداء",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "SourcePortName",
      headerName: "نام پورت مبداء",
      dataType: "text",
      isHeader: false,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: false },
    {
      field: "UtcTime",
      headerName: "تاریخ دفیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_processterminate: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: true },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_registryobjectaddordelete: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "EventType",
      headerName: "نوع رخداد",
      dataType: "text",
      isHeader: false,
    },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "TargetObject",
      headerName: "شیء هدف",
      dataType: "text",
      isHeader: true,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: false },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_registryobjectrenamed: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "EventType",
      headerName: "نوع رخداد",
      dataType: "text",
      isHeader: false,
    },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "NewName",
      headerName: "نام جدید",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "TargetObject",
      headerName: "شیء هدف",
      dataType: "text",
      isHeader: true,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: false },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_sysmon_registryvalueset: [
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "SysmonEventID",
      headerName: "شناسه ناظر رخداد های ویندوز",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "Details",
      headerName: "جزئیات",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "EventType",
      headerName: "نوع رخداد",
      dataType: "text",
      isHeader: false,
    },
    { field: "Image", headerName: "فایل", dataType: "text", isHeader: true },
    {
      field: "ProcessGuid",
      headerName: "شناسه یکتای پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "ProcessId",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "RuleName",
      headerName: "نام قانون",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "TargetObject",
      headerName: "شیء هدف",
      dataType: "text",
      isHeader: true,
    },
    { field: "User", headerName: "کاربر", dataType: "text", isHeader: false },
    {
      field: "UtcTime",
      headerName: "تاریخ دقیق",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_network_connectinfo: [
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "tick_time",
      headerName: "تاریخ پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "destination_ip_v4",
      headerName: "آدرس مقصد",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "destination_ip_v6",
      headerName: "آدرس نسخه ۶ مقصد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "destination_port",
      headerName: "پورت مقصد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "is_ip_v6",
      headerName: "وضعیت آدرس نسخه ۶",
      dataType: "checkbox",
      isHeader: false,
    },
    {
      field: "protocol",
      headerName: "پروتکل",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "source_ip_v4",
      headerName: "آدرس مبداء",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "source_ip_v6",
      headerName: "آدرس نسخه ۶ مبداء",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "source_port",
      headerName: "پورت مبداء",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_process_loadedimage: [
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "tick_time",
      headerName: "تاریخ پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "agent_ip",
      headerName: "آدرس عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "processImageFile",
      headerName: "آدرس فایل پردازه",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "processLoadedImageFile",
      headerName: "آدرس فایل بارگذاری شده پردازه",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  agents: [
    {
      field: "computer_name",
      headerName: "نام میزبان",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "local_endpoint_ip_address",
      headerName: "آدرس IP",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_core_version",
      headerName: "نسخه میزبان",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "last_time",
      headerName: "آخرین زمان فعالیت",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "status",
      headerName: "وضعیت",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "license_status",
      headerName: "وضعیت لایسنس",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP سیستم",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "hardware_token",
      headerName: "شناسه سخت افزاری",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "host_name",
      headerName: "نام هاست",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "node_name",
      headerName: "نام گره",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "dc_name",
      headerName: "نام دامنه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "agent_last_update_time",
      headerName: "آخرین زمان به روز رسانی",
      dataType: "date",
      isHeader: false,
    },
    {
      field: "agent_last_update_version",
      headerName: "آخرین نسخه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "system_local_time",
      headerName: "زمان سیستم",
      dataType: "date",
      isHeader: false,
    },
  ],
  quarantined_files: [
    {
      field: "accessed_file_path",
      headerName: "نام فایل دسترسی یافته",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "pid",
      headerName: "شماره فرآیند",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "score",
      headerName: "امتیاز",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    { field: "uuid", headerName: "شناسه", dataType: "text", isHeader: false },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_process_file_path",
      headerName: "مسیر فایل پردازه والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "quarantine_time",
      headerName: "تاریخ قرنطینه",
      dataType: "date",
      isHeader: false,
    },
    {
      field: "quarantine_reason",
      headerName: "دلیل قرنطینه",
      dataType: "date",
      isHeader: false,
    },
    {
      field: "file_size",
      headerName: "حجم فایل",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "file_name",
      headerName: "نام فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "tag", headerName: "تکنیک", dataType: "text", isHeader: true },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "hash_md5",
      headerName: "هش MD5",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "hash_sha256",
      headerName: "هش SHA256",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_filesystem_closefile: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "file_path",
      headerName: "مسیر فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_guid",
      headerName: "شناسه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_type",
      headerName: "نوع منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_device",
      headerName: "دستگاه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: true },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_filesystem_createfile: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "file_path",
      headerName: "مسیر فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_guid",
      headerName: "شناسه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_type",
      headerName: "نوع منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_device",
      headerName: "دستگاه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: true },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_filesystem_datareadfull: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "file_path",
      headerName: "مسیر فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "file_raw_hash",
      headerName: "هش خام فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_guid",
      headerName: "شناسه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_type",
      headerName: "نوع منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_device",
      headerName: "دستگاه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: true },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_filesystem_datawritefull: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "file_path",
      headerName: "مسیر فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "file_raw_hash",
      headerName: "هش خام فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_guid",
      headerName: "شناسه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_type",
      headerName: "نوع منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_device",
      headerName: "دستگاه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: true },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_filesystem_deletefile: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "file_path",
      headerName: "مسیر فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_guid",
      headerName: "شناسه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_type",
      headerName: "نوع منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_device",
      headerName: "دستگاه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: true },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_filesystem_filedatachange: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "file_path",
      headerName: "مسیر فایل",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_guid",
      headerName: "شناسه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_type",
      headerName: "نوع منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "file_volume_device",
      headerName: "دستگاه منبع فایل",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: true },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_process_createprocess: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "process_creation_time",
      headerName: "تاریخ ایجاد پردازه",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_image_file",
      headerName: "مسیر فایل پردازه",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_process_id",
      headerName: "شناسه پردازه والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "process_user_sid",
      headerName: "شناسه کاربر پردازه",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "process_creator_pid",
      headerName: "شناسه پردازه ایجاد کننده",
      dataType: "number",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "process_cmd_line",
      headerName: "خط فرمان پردازه",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_process_deleteprocess: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "process_deletion_time",
      headerName: "تاریخ حذف پردازه",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "process_exit_code",
      headerName: "کد خروج پردازه",
      dataType: "number",
      isHeader: true,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_process_openprocess: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "target_process_pid",
      headerName: "شناسه پردازه هدف",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "access_mask",
      headerName: "پوشش دسترسی یافته",
      dataType: "number",
      isHeader: true,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_registry_createkey: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "registry_path",
      headerName: "آدرس رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_registry_deletekey: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "registry_path",
      headerName: "آدرس رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_registry_deletevalue: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "registry_path",
      headerName: "آدرس رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "registry_name",
      headerName: "نام رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_registry_keynamechanged: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "registry_path",
      headerName: "آدرس رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "new_key_name",
      headerName: "نام جدید کلید",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  driver_registry_keyvalueset: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "process_is_evaluated",
      headerName: "وضعیت ارزیابی پردازه",
      dataType: "checkbox",
      isHeader: true,
    },
    {
      field: "registry_path",
      headerName: "آدرس رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "registry_name",
      headerName: "نام رجیستری",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "tick_time",
      headerName: "زمان پردازنده",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "driver_type",
      headerName: "نوع درایور",
      dataType: "text",
      isHeader: false,
    },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  etw_network_connectionattemptedinfo: [
    {
      field: "timestamp",
      headerName: "تاریخ",
      dataType: "date",
      isHeader: true,
    },
    {
      field: "process_id",
      headerName: "شناسه پردازه",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "src_ip",
      headerName: "آدرس مبداء",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "dest_ip",
      headerName: "آدرس مقصد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "src_port",
      headerName: "پورت مبداء",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "dest_port",
      headerName: "پورت مقصد",
      dataType: "number",
      isHeader: true,
    },
    {
      field: "etw_type",
      headerName: "نوع ناظر رخداد های ویندوز",
      dataType: "text",
      isHeader: true,
    },
    {
      field: "agent_ip",
      headerName: "آدرس IP عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "radar_event_entry_type",
      headerName: "نوع رخداد رادار",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "agent_id",
      headerName: "شناسه عامل",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "connection_id",
      headerName: "شناسه اتصال",
      dataType: "number",
      isHeader: false,
    },
    { field: "size", headerName: "حجم", dataType: "number", isHeader: false },
    { field: "event", headerName: "رخداد", dataType: "text", isHeader: false },
    {
      field: "target_image_filepath",
      headerName: "مسیر فایل هدف",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_image_filepath",
      headerName: "مسیر فایل والد",
      dataType: "text",
      isHeader: false,
    },
    {
      field: "parent_pid",
      headerName: "شناسه فرآیند والد",
      dataType: "number",
      isHeader: false,
    },
    {
      field: "extra_info",
      headerName: "اطلاعات اضافی",
      dataType: "text",
      isHeader: false,
    },
  ],
  multiav: [
    { field: 'file_name', headerName: 'نام فایل', dataType: 'text', isHeader: true },
    { field: 'agent_id', headerName: 'شناسه عامل', dataType: 'text', isHeader: true },
    { field: 'agent_ip', headerName: 'آدرس فرستنده', dataType: 'text', isHeader: true },
    { field: 'scan_id', headerName: 'شناسه پویش', dataType: 'text', isHeader: true },
    { field: 'scan_time', headerName: 'زمان پویش', dataType: 'date', isHeader: true },
    {
      field: 'upload_file_source',
      headerName: 'منبع آپلود فایل',
      dataType: 'text',
      isHeader: true,
    },
  ],
  multiav_details: [
    { field: 'title', headerName: 'عنوان', dataType: 'text', isHeader: true },
    { field: 'status', headerName: 'وضعیت', dataType: 'text', isHeader: true },
    { field: 'infected', headerName: 'میزان آلودگی', dataType: 'text', isHeader: true },
    { field: 'error', headerName: 'خطا', dataType: 'text', isHeader: true },
    { field: 'version', headerName: 'نسخه', dataType: 'text', isHeader: true },
    { field: 'updated_time', headerName: 'آخرین وضعیت', dataType: 'text', isHeader: true },
  ],
  ai: [
    { field: 'file_name', headerName: 'نام فایل', dataType: 'text', isHeader: true },
    { field: 'MD5_hash', headerName: 'MD5 هش', dataType: 'text', isHeader: true },
    { field: 'SHA256_hash', headerName: 'SHA256 هش', dataType: 'text', isHeader: true },
    { field: 'scan_time', headerName: 'زمان پویش', dataType: 'date', isHeader: true },
    { field: 'agent_id', headerName: 'شناسه عامل', dataType: 'text', isHeader: true },
    { field: 'agent_ip', headerName: 'آدرس فرستنده', dataType: 'text', isHeader: true },
  ],
  all_events: [
    { field: 'event_title', headerName: 'عنوان رخداد', dataType: 'text', isHeader: true },
    { field: 'timestamp', headerName: 'تاریخ رخداد', dataType: 'date', isHeader: true },
    { field: 'agent_ip', headerName: 'آدرس IP', dataType: 'text', isHeader: true },
    { field: 'computer_name', headerName: 'سیستم', dataType: 'text', isHeader: true },
    { field: 'agent_core_version', headerName: 'نسخه سیستم', dataType: 'text', isHeader: true },
    { field: 'event_type', headerName: 'نوع رخداد', dataType: 'text', isHeader: true },
  ],
  inspectAi: [
    { field: 'file_name', headerName: 'نام فایل', dataType: 'text', isHeader: true },
    {
      field: 'MD5_hash',
      headerName: 'MD5 هش',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'SHA256_hash',
      headerName: 'SHA256 هش',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'agent_id',
      headerName: 'شناسه عامل',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'agent_ip',
      headerName: 'آدرس IP',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'scan_time',
      headerName: 'زمان پویش',
      dataType: 'date',
      isHeader: true,
    },
  ],
  inspectQuarantined: [
    {
      field: 'accessed_file_path',
      headerName: 'نام فایل دسترسی یافته',
      dataType: 'text',
      isHeader: true,
    },
    { field: 'agent_id', headerName: 'شناسه عامل', dataType: 'text', isHeader: true },
    {
      field: 'hash_md5',
      headerName: 'MD5 هش',
      dataType: 'text',
      isHeader: true,
    },
    { field: 'pid', headerName: 'شماره فرآیند', dataType: 'number', isHeader: true },
    {
      field: 'score',
      headerName: 'امتیاز',
      dataType: 'number',
      isHeader: true,
    },
    { field: 'tag', headerName: 'تکنیک', dataType: 'text', isHeader: true },
    {
      field: 'timestamp',
      headerName: 'تاریخ رخداد',
      dataType: 'date',
      isHeader: true,
    },
  ],

  inspect_events: [
    { field: 'event_title', headerName: 'عنوان رخداد', dataType: 'text', isHeader: true },
    {
      field: 'timestamp',
      headerName: 'تاریخ رخداد',
      dataType: 'date',
      isHeader: true,
    },
    {
      field: 'agent_ip',
      headerName: 'آدرس IP',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'computer_name',
      headerName: 'سیستم',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'agent_core_version',
      headerName: 'نسخه سیستم',
      dataType: 'text',
      isHeader: true,
    },
    {
      field: 'event_type',
      headerName: 'نوع رخداد',
      dataType: 'text',
      isHeader: true,
    },

    { field: 'registry_name', headerName: 'نام رجیستری', dataType: 'text', isHeader: false },
    { field: 'registry_path', headerName: 'آدرس رجیستری', dataType: 'text', isHeader: false },

    {
      field: 'tick_time',
      headerName: 'زمان پردازنده',
      dataType: 'number',
      isHeader: false,
    },
    { field: 'agent_id', headerName: 'شناسه عامل', dataType: 'text', isHeader: false },
    {
      field: 'parent_image_filepath',
      headerName: 'مسیر فایل والد',
      dataType: 'text',
      isHeader: false,
    },

    {
      field: 'parent_pid',
      headerName: 'شناسه فرآیند والد',
      dataType: 'number',
      isHeader: false,
    },
    { field: 'process_id', headerName: 'شناسه پردازه', dataType: 'number', isHeader: false },
    {
      field: 'radar_event_entry_type',
      headerName: 'نوع رخداد رادار',
      dataType: 'text',
      isHeader: false,
    },
    { field: 'driver_type', headerName: 'نوع درایور', dataType: 'text', isHeader: false },
    {
      field: 'target_image_filepath',
      headerName: 'مسیر فایل هدف',
      dataType: 'text',
      isHeader: false,
    },
    {
      field: 'process_is_evaluated',
      headerName: 'وضعیت ارزیابی پردازه',
      dataType: 'checkbox',
      isHeader: false,
    },
  ],
  quarantined_reason: [
    { field: 'event_headerName', headerName: 'عنوان رخداد', dataType: 'text', isHeader: true },
    { field: 'timestamp', headerName: 'تاریخ رخداد', dataType: 'date', isHeader: true },
    { field: 'agent_ip', headerName: 'آدرس IP', dataType: 'text', isHeader: true },
    { field: 'event_type', headerName: 'نوع رخداد', dataType: 'text', isHeader: true },
  ],
  filters: [
    { field: 'pid', headerName: 'شناسه', dataType: 'number', isHeader: true },
    { field: 'submit_time', headerName: 'تاریخ ایجاد', dataType: 'date', isHeader: true },
    { field: 'type', headerName: 'نوع فیلتر', dataType: 'text', isHeader: true },
    { field: 'priority', headerName: 'اولویت', dataType: 'number', isHeader: true },
  ],
  ad_list: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'ip_address', headerName: 'آدرس سرور', dataType: 'text', isHeader: true },
    { field: 'domain_url', headerName: 'آدرس دامنه', dataType: 'text', isHeader: true },
    { field: 'username', headerName: 'نام کاربری', dataType: 'text', isHeader: true },
    { field: 'status', headerName: 'وضعیت', dataType: 'checkbox', isHeader: true },
  ],
  ad_detail: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'name', headerName: 'نام گروه/کاربر', dataType: 'text', isHeader: true },
    { field: 'domain_url', headerName: 'آدرس دامنه', dataType: 'text', isHeader: true },
    { field: 'computer_name', headerName: 'نام کامپیوتر', dataType: 'text', isHeader: true },
  ],
  ad_computers: [
    { field: 'name', headerName: 'نام کامپیوتر', dataType: 'text', isHeader: true },
    { field: 'status', headerName: 'وضعیت', dataType: 'checkbox', isHeader: true },
    { field: 'domain_url', headerName: 'نام دامنه', dataType: 'text', isHeader: true },
    // { field: 'date_timestamp', headerName: 'تاریخ', dataType: 'date', isHeader: true },
  ],
  update_history: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'updateID', headerName: ' شناسه به روزرسانی', dataType: 'text', isHeader: true },
    { field: 'old_version', headerName: 'نسخه قبلی', dataType: 'text', isHeader: true },
    { field: 'new_version', headerName: 'نسخه جدید', dataType: 'text', isHeader: true },
    { field: 'status', headerName: 'وضعیت', dataType: 'checkbox', isHeader: true },
    { field: 'timestamp', headerName: 'تاریخ', dataType: 'date', isHeader: true },
  ],
  users: [
    { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'username', headerName: 'نام کاربری', dataType: 'text', isHeader: true },
    { field: 'email', headerName: 'پست الکترونیکی کاربر', dataType: 'text', isHeader: true },
    { field: 'created_time', headerName: 'تاریخ ایجاد', dataType: 'date', isHeader: true },
    { field: 'first_login_time', headerName: 'تاریخ اولین ورود', dataType: 'date', isHeader: true },
    { field: 'last_time', headerName: 'تاریخ آخرین فعالیت', dataType: 'date', isHeader: true },
    { field: 'role', headerName: 'سطح دسترسی', dataType: 'text', isHeader: true },
  ],
  unsuccessful_logins: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'username', headerName: 'نام کاربری', dataType: 'text', isHeader: true },
    { field: 'password', headerName: 'رمز عبور', dataType: 'text', isHeader: true },
    { field: 'ip_address', headerName: 'آدرس IP', dataType: 'text', isHeader: true },
    { field: 'agent', headerName: 'نام عامل', dataType: 'text', isHeader: true },
    { field: 'submit_time', headerName: 'تاریخ', dataType: 'date', isHeader: true },
  ],
  usersActivity: [
    { field: 'username', headerName: 'نام کاربری', dataType: 'text', isHeader: true },
    { field: 'datetime', headerName: 'تاریخ', dataType: 'date', isHeader: true },
    { field: 'path', headerName: 'مسیر', dataType: 'text', isHeader: true },
    { field: 'url_name', headerName: 'آدرس', dataType: 'text', isHeader: true },
    { field: 'action', headerName: 'عملیات', dataType: 'text', isHeader: true },
  ],
  roles: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'name', headerName: 'نام', dataType: 'text', isHeader: true },
  ],
  yara: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'name', headerName: 'نام', dataType: 'text', isHeader: true },
    { field: 'md5', headerName: 'هش MD5', dataType: 'text', isHeader: true },
    { field: 'created_time', headerName: 'تاریخ ایجاد', dataType: 'date', isHeader: true },
    { field: 'enabled', headerName: 'وضعیت', dataType: 'checkbox', isHeader: true },
    { field: 'content', headerName: 'محتوا', dataType: 'text', isHeader: false },
  ],
  sigma: [
    // { field: 'id', headerName: 'شناسه', dataType: 'number', isHeader: false },
    { field: 'name', headerName: 'نام', dataType: 'text', isHeader: true },
    { field: 'md5', headerName: 'هش MD5', dataType: 'text', isHeader: true },
    { field: 'created', headerName: 'تاریخ ایجاد', dataType: 'date', isHeader: true },
    { field: 'content', headerName: 'محتوا', dataType: 'text', isHeader: false },
  ],
  aiUpload: [
    { field: 'file_name', headerName: 'نام فایل', dataType: 'text', isHeader: true },
    { field: 'MD5_hash', headerName: 'هش MD5', dataType: 'text', isHeader: true },
    { field: 'SHA256_hash', headerName: 'هش SHA256', dataType: 'text', isHeader: true },
    { field: 'scan_time', headerName: 'زمان پویش', dataType: 'date', isHeader: true },
    { field: 'status', headerName: ' وضعیت', dataType: 'text', isHeader: true },
  ],
};
export const fieldsQueries: Field[] = [
  { field: 'timestamp', headerName: 'تاریخ', dataType: 'date', isHeader: false },
];

const {
  all_events,
  quarantined_files,
  agents,
  filters,
  ad_list,
  ad_detail,
  ad_computers,
  update_history,
  yara,
  sigma,
  users,
  roles,
  unsuccessful_logins,
  inspectQuarantined,
  inspect_events,
  inspectAi,
  usersActivity,
  multiav,
  multiav_details,
  ai,
  aiUpload,
} = headers;
export {
  all_events,
  quarantined_files,
  agents,
  filters,
  ad_list,
  ad_detail,
  ad_computers,
  update_history,
  yara,
  sigma,
  users,
  roles,
  unsuccessful_logins,
  inspectQuarantined,
  inspect_events,
  inspectAi,
  usersActivity,
  multiav,
  multiav_details,
  ai,
  aiUpload,
};
export default headers;
